### ISSUE TITLE
TypeOrm databaseService in RenderThread How?

### ISSUE THREAD

**Issue by aammfe** [CubikNeRubik/angular-electron-typeorm-starter#1]
Thanx Thanx Thanx For creating this Repo.

Hello!!!
my background is .net and I m new to web world.

1- from my understanding electron has two threads 
main , render and typeOrm should be running on main thread(to use file system for sqlite or mysql). but here I m seeing its happening in (render thread) AppComponent. how its working ?

2- where **databaseService** is being injected in first place ?

`export class AppComponent {
	users: User[] = [];
	displayedColumns: string[] = ['Id', 'FirstName', 'LastName', 'Age'];

firstName = '';
	lastName = '';
	age = '';
	constructor(private databaseService: DatabaseService) {
		this.getUsers();
	}`
 
bcs in AppModule provider is emptyArray 

![image](https://user-images.githubusercontent.com/11896817/48293710-39c75600-e4a2-11e8-8bf5-0811ddb4f24d.png)

Please Help and Thanx for this great repo. I could not tell How Much I am thankfull for it.

**Comment by CubikNeRubik** [comment]
Hello!

I am really glad that this repo useful for you.

1. You are right. DAL should be at main thread but if your app use only one window you can use it directly in render.

2.  In real `databaseService` injected to `root` immediately  at declaration 
```ts
@Injectable({
    providedIn: 'root'
})
export class DatabaseService {
    ...
}
```
