### ISSUE TITLE
upgrade to angular 8.0.3

### ISSUE THREAD

**Issue by MetaiR** [CubikNeRubik/angular-electron-typeorm-starter#2]
can u please provide a way to upgrade this starter pack to angular 7 or even a clue for doing that?

**Comment by MetaiR** [comment]
I create a project based on this repo and update it,
I even remove extra things to have a very simple angular + electron + typeorm project
I also try to keep it up to date with 3d party integrations
https://github.com/MetaiR/angular-electron-typeorm

**Comment by CubikNeRubik** [comment]
Hi @MetaiR,
Sorry for the long delay, I am going to update versions soon. If you already did it - feel free to make PR

**Comment by MetaiR** [comment]
hi,
I did it and create a project and repo based on it, now the problem is the upgrade to version 8 and enables Ivy and I am working on that too

**Comment by CubikNeRubik** [comment]
I will be happy to hear something about your success

**Comment by MetaiR** [comment]
Thanks, I am working on it.
there is a problem, Ivy isn't ready yet and Angular recommends v8.1.0 for using  Ivy (which it also isn't ready and doesn't publish yet but it is on beta stage and will come out soon)

angular 8 also had some changes so I think, it is better to wait until version 8.1.0, then going for the update.
but maybe I upgrade to version 8.0.3 until then.
in any case, I will keep ur legacy. thanks for ur good work

**Comment by CubikNeRubik** [comment]
I have prepared pull request #4 with version upgrade

**Comment by MetaiR** [comment]
wow, it is perfect,
I guess it is time to switch back people from mine to this repo again,
I think I have to create branches and send u pull request for them,
for example, there is a bunch of stupid  bugs in typeorm, and I had to create other forms of this repo like a repo just contains mariadb drive connector and working with sql queries and etc

**Comment by CubikNeRubik** [comment]
@MetaiR I want to left SQLite in that starter. It should be a standalone application without the requirement of db server.
