### ISSUE TITLE
Error after run "npm install" command

### ISSUE THREAD

**Issue by amin-pi** [CubikNeRubik/angular-electron-typeorm-starter#5]
download new version from "branches -> angular-version-update" and run "npm install" command in root
after install dependencies, hapend this error:
![err](https://user-images.githubusercontent.com/19885519/59825182-92b87000-9348-11e9-8b9b-f1fb6a29e967.png)

**Comment by CubikNeRubik** [comment]
Hi @amin-pi,
What version of node and npm do you use?

**Comment by amin-pi** [comment]
> Hi @amin-pi,
> What version of node and npm do you use?

node:  v10.15.3
npm:  6.9.0

**Comment by CubikNeRubik** [comment]
I used node version v10.16.0 and the same version of npm, everything works fine.
I can suggest you run `npm run postinstall`. It might help.

**Comment by amin-pi** [comment]
> I use node version v10.16.0 and the same version of npm, everything works fine.
> I can suggest you run `npm run postinstall`. It might help.

thanks,
I tested `npm run postinstall`, but did not make a difference.
There is still the same error.

**Comment by CubikNeRubik** [comment]
@amin-pi, just test it on three different PC everything is work well. Maybe it is something with your environment.

**Comment by CubikNeRubik** [comment]
@amin-pi try just to run `npm i sqlite3@4.0.9`, the problem should be here.

**Comment by amin-pi** [comment]
thanks @CubikNeRubik ,
i'm used the last commit on your branch.
it's ok. resolved the problem.
