### ISSUE TITLE
SQLITE_ERROR: near "}" (solved)

### ISSUE THREAD

**Issue by AdditionAddict** [CubikNeRubik/angular-electron-typeorm-starter#7]
Just wanted to make a note in case anyone else encounters same issue but when I build executable TypeOrm seems to not use any table names and after turning logging on I saw I was getting the following:-
```
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('e')
``` 
or in my case
```
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('t', 't', 't', 't', 't')
```

The error was `SQLITE_ERROR: near "}"`

I managed to fix by manually putting table names in i.e.
```
@Entity({ name: "user"})
export class User extends BaseEntity {
  ...
}
```

**Comment by CubikNeRubik** [comment]
Hi @AdditionAddict,
Thanks for writing. I am not sure that understand what was a problem (can you elaborate a little bit?). But that this will help someone with the same issue in the future.

**Comment by AdditionAddict** [comment]
Hi @CubikNeRubik, I'll duplicate the issue later this evening and post the screenshots but to elaborate the starter works out of the box when running `npm start` but issue is after running `npm run electron:windows` to get executable. My queries werent working and logging the connection showed `entities: [Employee]` in `DatabaseService` was replaced by `entities: [t()]`. Explicitly putting tbale names like `{ name: "user"}` seemed to fix this.

**Comment by AdditionAddict** [comment]
@CubikNeRubik To replicate issue:

```
> cd Desktop
> git clone https://github.com/CubikNeRubik/angular-electron-typeorm-starter
> cd angular-electron-typeorm-starter
> npm i --verbose
```

Then turn TypeORM logging fully on via `loggin: "all"` in `DatabaseService`

![image](https://user-images.githubusercontent.com/48436581/61317222-7bab5780-a7fa-11e9-9720-a64fc36e27f0.png)

**Development - no issue**
```
> npm start
```
![image](https://user-images.githubusercontent.com/48436581/61317299-a39abb00-a7fa-11e9-8706-c91105fadd01.png)

**Note**: `query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user')`
________________________________________________________________________________________________^

**Windows executable**
```
> npm run electron:windows
```
![image](https://user-images.githubusercontent.com/48436581/61317378-c5943d80-a7fa-11e9-9892-e9ab3d1c68ea.png)
Note: `query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('e')`
________________________________________________________________________________________________^

For one table there's no issue but this leads to obscure errors for multiple tables.

**Comment by CubikNeRubik** [comment]
@AdditionAddict  Thanks 
I've added fix to master

**Comment by AdditionAddict** [comment]
@CubikNeRubik Apologies, this is not fixed just by renaming tables.

Per link below
https://typeorm.io/#/faq/how-to-use-webpack-for-the-backend
..."since Webpack 4, when using mode: 'production', files are optimized by default which includes mangling your code in order to minimize file sizes."

Putting the following in `extra-webpack.config.js` seems to partly solve
```
    optimization: {
        minimize: false,
    },
```

I'll research and get back to you with an update once I've fully researched this (though I'm lost on webpack aspects).
